### ISSUE TITLE
Can you merge this feature into react-native-material-kit project

### ISSUE THREAD

**Issue by haripal143** [shahen94/react-native-switch#7]
https://github.com/xinthink/react-native-material-kit

**Comment by shahen94** [comment]
Hi @haripal143. This is a separate project with absolute different code structure.
https://github.com/xinthink/react-native-material-kit written native for each platform, so that'd be great to keep that fully native.
This switch component build fully with RN with JS, So this will be more simply to keep this two libraries in separate repositories.
